### ISSUE TITLE
Missing unary ops for swizzler type

### ISSUE THREAD

**Issue by attilaz** [valentingalea/vml#2]
I guess this is a known limitation: https://github.com/valentingalea/vml/blob/master/vml/detail/swizzler.h#L38

Things like
```
vec4 q;
vec4 q2 = vec4(-q.xyz,q.w);
```

and
```
vec3 v;
v.xz *= 0.5;
```

are not working now.

Are they planned to be implemented?

**Comment by valentingalea** [comment]
Thanks for reporting it! I'll take a look - how urgent / blocking is this for you @attilaz ?

**Comment by attilaz** [comment]
After reporting the issue I have added things like this to the swizzler:

```
	swizzler& operator +=(const vector_type& v)
	{
		*this = vector_type(*this) + v;
		return *this;
	}

```

It seems to be working (at least for my use case). Not sure if this is a proper/general solution.

**Comment by valentingalea** [comment]
@attilaz check the PR for a more general solution (but not complete). Will you need things like `v.xy += v.xx`?

Thanks btw for using the library and I'm glad it's helpful!

**Comment by attilaz** [comment]
Thanks for this library. It was easy to integrate and it is fun to use!

I have tried the PR and had some problems.
I have things like `v.xy += v.zw; `that doesn't work.

And also had problems with statements like this:
`v.xyz += u.xyz * 2.0f;
`

**Comment by valentingalea** [comment]
Recheck the PR - everything should work now!

**Comment by attilaz** [comment]
It works well now. Thanks!
