### ISSUE TITLE
swizzle += incorrect result

### ISSUE THREAD

**Issue by attilaz** [valentingalea/vml#4]
```
	vec3 a(1.0,2.0,3.0);
	vec2 b(4.0,4.0);
	a.xz += b;

```
a is (5.0, 2.0, 3.0) instead of (5.0,2.0,7.0)

**Comment by valentingalea** [comment]
fixed directly in master 23ae9766e552f96dfcebe9a561b40002ccdeb942

**Comment by attilaz** [comment]
thanks for the quick fix!
